### ISSUE TITLE
QUESTION: links in sent mail works with gmail address but not gandi.net ?

### ISSUE THREAD

**Issue by H4E** [jlm2017/mosaico-standalone#14]
Hello, I have noticed a strange behavior when testing mosaico-standalone.
I have tried to test to send email to  2 of my mail addresses: one on gandi server, the other one at gmail.
The gmail email received contains correct buttons links,  
The gandi one have all links replaced by https://webmail.eu.com/#NOP

Note: I have sent the template mail using my gandi address to both addresses mentioned before...
Is it reproducible from your side ?

**Comment by guilro** [comment]
Thanks for the report :) I'll try to reproduce it.
