### ISSUE TITLE
Template : button lines with variable number of buttons

### ISSUE THREAD

**Issue by guilro** [jlm2017/mosaico-standalone#2]
Ref to https://github.com/jlm2017/versafix-jlm2017/issues/1.

**Comment by H4E** [comment]
Made a pull request to know if it can fit: https://github.com/jlm2017/mosaico-standalone/pull/13
For now it only can display max 3 buttons in a line as I havent found a way to make a loop in current template engine.
So it is more a draft to know if it can be on the right way and have comments to iterate over.

**Comment by guilro** [comment]
The `mosaico` directory should not be modified on the repository. It is just a copy from upstream [Mosaico](https://github.com/voidlabs/mosaico/).

The pull request should be made against the repository for [JLM 2017 Mosaico template](https://github.com/jlm2017/versafix-jlm2017), refering this issue : https://github.com/jlm2017/versafix-jlm2017/issues/1.
